"""
DGA DETECTOR — v29.44 (improvement catalog §5a)
================================================================================
Algorithmically Generated Domain (DGA) detection using Shannon entropy,
character distribution analysis, and n-gram scoring.

Detects C2 domains generated by DGA algorithms (Cryptolocker, Conficker,
Zeus, Bedep, Matsnu, Suppobox, etc.) before they are resolved.
"""
from __future__ import annotations

import hashlib
import logging
import math
import re
from typing import Dict, List, Tuple

_log = logging.getLogger(__name__)

# English character frequency for scoring deviation
_ENGLISH_FREQ: Dict[str, float] = {
    'a': 0.0817, 'b': 0.0149, 'c': 0.0278, 'd': 0.0425, 'e': 0.1270,
    'f': 0.0223, 'g': 0.0202, 'h': 0.0609, 'i': 0.0697, 'j': 0.0015,
    'k': 0.0077, 'l': 0.0403, 'm': 0.0241, 'n': 0.0675, 'o': 0.0751,
    'p': 0.0193, 'q': 0.0010, 'r': 0.0599, 's': 0.0633, 't': 0.0906,
    'u': 0.0276, 'v': 0.0098, 'w': 0.0236, 'x': 0.0015, 'y': 0.0197,
    'z': 0.0007,
}

# Common TLDs that DGA domains rarely use
_COMMON_TLDS = {'.com', '.org', '.net', '.edu', '.gov', '.co.uk'}

# Well-known legitimate domains that score high on entropy but are safe
_WHITELIST = {
    'google.com', 'facebook.com', 'youtube.com', 'amazon.com',
    'microsoft.com', 'apple.com', 'netflix.com', 'twitter.com',
    'instagram.com', 'linkedin.com', 'github.com', 'stackoverflow.com',
}


def shannon_entropy(text: str) -> float:
    """Shannon entropy of a string (bits per character)."""
    if not text:
        return 0.0
    freq: Dict[str, int] = {}
    for ch in text:
        freq[ch] = freq.get(ch, 0) + 1
    length = len(text)
    return -sum((c / length) * math.log2(c / length) for c in freq.values())


def consonant_ratio(text: str) -> float:
    """Ratio of consonants to total alphabetic characters."""
    alpha = [c for c in text.lower() if c.isalpha()]
    if not alpha:
        return 0.0
    vowels = set('aeiou')
    consonants = sum(1 for c in alpha if c not in vowels)
    return consonants / len(alpha)


def digit_ratio(text: str) -> float:
    """Ratio of digits to total characters."""
    if not text:
        return 0.0
    return sum(1 for c in text if c.isdigit()) / len(text)


def bigram_score(text: str) -> float:
    """Score based on common English bigram frequency deviation (0-1, lower = more DGA-like)."""
    common_bigrams = {
        'th', 'he', 'in', 'er', 'an', 're', 'on', 'at', 'en', 'nd',
        'ti', 'es', 'or', 'te', 'of', 'ed', 'is', 'it', 'al', 'ar',
    }
    if len(text) < 2:
        return 1.0
    total_bigrams = len(text) - 1
    matching = sum(1 for i in range(total_bigrams)
                   if text[i:i + 2].lower() in common_bigrams)
    return matching / max(total_bigrams, 1)


class DGAResult:
    """Result of a DGA analysis for a single domain."""

    __slots__ = ('domain', 'entropy', 'consonant_ratio', 'digit_ratio',
                 'bigram_score', 'length', 'is_dga', 'confidence')

    def __init__(self, domain: str, entropy: float, consonant_ratio: float,
                 digit_ratio: float, bigram_score: float, length: int,
                 is_dga: bool, confidence: float):
        self.domain = domain
        self.entropy = entropy
        self.consonant_ratio = consonant_ratio
        self.digit_ratio = digit_ratio
        self.bigram_score = bigram_score
        self.length = length
        self.is_dga = is_dga
        self.confidence = confidence

    def __repr__(self) -> str:
        return (f'DGAResult({self.domain!r}, dga={self.is_dga}, '
                f'confidence={self.confidence:.2f})')


class DGADetector:
    """DGA domain detector using multi-factor scoring."""

    def __init__(self, entropy_threshold: float = 3.8,
                 consonant_threshold: float = 0.6,
                 digit_threshold: float = 0.3,
                 bigram_threshold: float = 0.15,
                 min_domain_length: int = 8):
        self._entropy_threshold = entropy_threshold
        self._consonant_threshold = consonant_threshold
        self._digit_threshold = digit_threshold
        self._bigram_threshold = bigram_threshold
        self._min_length = min_domain_length

    def analyze(self, domain: str) -> DGAResult:
        """Analyze a single domain for DGA characteristics."""
        domain = domain.lower().strip()
        # Strip TLD for scoring (keep for reporting)
        parts = domain.rsplit('.', 1)
        sld = parts[0] if len(parts) > 1 else domain
        # Remove non-alphanumeric (dots, hyphens)
        sld_clean = re.sub(r'[^a-z0-9]', '', sld)

        entropy = shannon_entropy(sld_clean)
        c_ratio = consonant_ratio(sld_clean)
        d_ratio = digit_ratio(sld_clean)
        b_score = bigram_score(sld_clean)
        length = len(sld_clean)

        # Scoring: multiple indicators must be present for DGA classification
        score = 0.0
        if length >= self._min_length:
            score += 0.2
        if entropy > self._entropy_threshold:
            score += 0.25
        if c_ratio > self._consonant_threshold:
            score += 0.25
        if d_ratio > self._digit_threshold:
            score += 0.15
        if b_score < self._bigram_threshold:
            score += 0.15
        if domain in _WHITELIST:
            score = 0.0

        is_dga = score >= 0.6
        confidence = min(1.0, score)
        return DGAResult(domain, entropy, c_ratio, d_ratio, b_score,
                         length, is_dga, confidence)

    def analyze_batch(self, domains: List[str]) -> List[DGAResult]:
        """Analyze multiple domains. Returns DGA-flagged results only."""
        return [r for r in (self.analyze(d) for d in domains) if r.is_dga]


__all__ = ['DGADetector', 'DGAResult', 'shannon_entropy', 'consonant_ratio',
           'bigram_score']